In [2]:
# Import numpy as np
import numpy as np
# Create two arrays "a" and "b"
a = np.array([1,2,3,2,3,4,3,4,5,6])
b= np.array([7,2,10,2,7,4,9,4,9,8])
# Find the distinct common values between array "a" and "b"
print(np.intersect1d(a,b))

[2 4]


In [4]:
# Create array "a" in a sequencing range from 1 to 15 not including 0
a = np.arange(1,16)
# Reshape the array in a 3x5 sequence 
a = a.reshape(3,5)


In [5]:
# Print array "a"
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
# Reshape the array "a" in a 5x3 sequence 
a.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [7]:
# Create two arrays "a" and "b"
a = np.array([12,5,7,15,3,1,8])
b = np.array([14,6,3,11,19,12,5])

In [9]:
# Create array "a" which includes elements in a that are not in b
a = np.setdiff1d(a,b)
# Print the array "a"
a

array([ 1,  7,  8, 15])

In [10]:
# Create an array called "c" to collect all of miles have been traveled each day including 4 days - due to either weather conditions or personal fatigue/soreness

c = np.array([55,55,65,78,54,0,65,55,63,27,57,0,44,33,44,56,76,0,43,24,25,34,0,55,36,45,23,34,44,55,32,43,45,38,40])



In [11]:
# Create another array called "d" to accumulate the miles from first day to the last day
d = np.add.accumulate(c)
d

array([  55,  110,  175,  253,  307,  307,  372,  427,  490,  517,  574,
        574,  618,  651,  695,  751,  827,  827,  870,  894,  919,  953,
        953, 1008, 1044, 1089, 1112, 1146, 1190, 1245, 1277, 1320, 1365,
       1403, 1443], dtype=int32)

In [14]:
# Create another array called "day_distance" by using diff function to show the total miles rode each day
day_distance = np.diff(d)

# Show the total miles rode each day 
day_distance

array([55, 65, 78, 54,  0, 65, 55, 63, 27, 57,  0, 44, 33, 44, 56, 76,  0,
       43, 24, 25, 34,  0, 55, 36, 45, 23, 34, 44, 55, 32, 43, 45, 38, 40],
      dtype=int32)

1. Google the distance between New York City to Key West
2. Making up the data which is also including four days no cycling
3. Using the accumulate function to add up miles from each day
4. Using the diff function to figure out the miles traveled each day 

In [15]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

In [16]:
# Create another array call "max_water" and extract the water consumption from array "nyc_water"
max_water = nyc_water[:,2]

# Find out the maximum yearly NYC consumption of water in millions of gallons per day
np.max(max_water)

1512.0

In [17]:
# Create another array call "calendar_year" 
calendar_year = np.shape(nyc_water)
# Call the tuple "Calendar_year" by using index - Find out how many calendar years are represented within this data set - "39 calendar years"
calendar_year[0]

39

In [18]:
# Create another array call "cap_water" and extract  per capita daily water consumption from array "nyc_water"
cap_water = nyc_water[:,3]
# The mean of the per capita daily water consumption
np.mean(cap_water)

160.30769230769232

In [19]:
# The standard deviation of the per capita daily water consumption
np.std(cap_water)

31.51894330370624

In [21]:
# Use Numpy diff functions to find all of differences between each rows looping from the first one to the last
difference = np.diff(nyc_water, axis = 0)

In [22]:
# Print the result "difference"
difference

array([[     1. , -30461. ,     -6. ,      0. ],
       [     1. ,  17602. ,   -197. ,    -28. ],
       [     1. ,  19864. ,     73. ,      9. ],
       [     1. ,  72119. ,     42. ,      4. ],
       [     1. ,  53290. ,     41. ,      5. ],
       [     1. ,  39540. ,   -139. ,    -21. ],
       [     1. ,  45192. ,     25. ,      3. ],
       [     1. ,  23230. ,     96. ,     12. ],
       [     1. ,  11243. ,     37. ,      5. ],
       [     1. ,  -9544. ,    -82. ,    -11. ],
       [     1. ,  -8525. ,     22. ,      3. ],
       [     1. ,  38851. ,     45. ,      5. ],
       [     1. ,  54443. ,   -100. ,    -15. ],
       [     1. ,  77222. ,     -0.5,     -2. ],
       [     1. ,  64292. ,    -10.8,     -3. ],
       [     1. ,  62582. ,    -32. ,     -5. ],
       [     1. ,  64772. ,    -27.8,     -5. ],
       [     1. ,  75631. ,    -92.4,    -14. ],
       [     1. ,  84816. ,     14. ,      0. ],
       [     1. ,  89401. ,     17.7,      1. ],
       [     1. ,  6

In [23]:
# Slicing the arrays by calling the index '1' which is the second column and looping from the first rows to the last
# Saved that to a variable called "pop_diff"
pop_diff = difference[:,1]

In [24]:
# Print the array "pop_diff" which shows the increase or decrease in population from year to year
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])